<a href="https://colab.research.google.com/github/swapnil14g/random_practice/blob/main/stats2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=np.random.randint(low=0,high=100, size=(3,4))
names=['Eleanor', 'Chidi', 'Tahani', 'Jason']
data_set=pd.DataFrame(data=data,columns=names)

In [ ]:
x=np.array([[12,3,25]])
x

array([[12,  3, 25]])

In [ ]:
x.shape

(1, 3)

# Transpose

In [ ]:
x_t=x.T
print(x_t)
x_t.shape

[[12]
 [ 3]
 [25]]


(3, 1)

In [1]:
import torch

In [7]:
x_t=torch.tensor([[1,2,3]])
x_t.T

tensor([[1],
        [2],
        [3]])